#! /bin/sh

export XDG_CONFIG_DIRS=$(dirname $0)

mkdir -p cockpit
cat >cockpit/cockpit.conf <<EOF
[Webservice]
LoginTitle = Foreman Cockpit
UrlRoot = /webcon/

[Bearer]
Action = remote-login-ssh

[SSH-Login]
command = ./foreman-cockpit-session

[OAuth]
Url = /api/cockpit_redirect
EOF

if [ ! -d ./cockpit/ws-certs.d ]; then
    mkdir ./cockpit/ws-certs.d
    remotectl certificate --ensure
fi

/usr/libexec/cockpit-ws --port 9999 --no-tls
